In [27]:
#==============================================================================
# Import libraries
#==============================================================================
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [28]:
#==============================================================================
# import the dataset of flat prices
#==============================================================================

flatdata = pd.read_csv ('Price.csv')
X = flatdata.iloc [:,:-1].values
y = flatdata.iloc [:,1].values

In [29]:
flatdata.head()

Area (sqft)  Price ($)
0         2000      88600
1         1600      71600
2         1980      93300
3         1840      84300
4         1710      80600

In [30]:
flatdata.shape

(40, 2)

In [31]:
#==============================================================================
# split the dataset into training and test set. We will use 80/20 approach
#==============================================================================

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = 1/4, random_state = 0)



In [32]:
#==============================================================================
# Fitting the Linear Regression algo to the Training set
#==============================================================================

from sklearn.linear_model import LinearRegression
regressoragent = LinearRegression()
regressoragent.fit (X_train, y_train)            


LinearRegression()

In [33]:
regressoragent.intercept_

16531.360415393996

In [34]:
regressoragent.coef_

array([37.71678375])

In [35]:
#==============================================================================
# Fitting the Lasso Regression algo to the Training set
#==============================================================================

from sklearn.linear_model import Lasso
Lasso_Reg = Lasso()
Lasso_Reg.fit (X_train, y_train )    

Lasso()

In [36]:
#==============================================================================
# Fitting the Ridge Regression algo to the Training set
#==============================================================================

from sklearn.linear_model import Ridge
Ridge_Reg = Ridge()
Ridge_Reg.fit (X_train, y_train )    

Ridge()

In [37]:
#==============================================================================
# Fitting the ElasticNet Regression algo to the Training set
#==============================================================================

from sklearn.linear_model import ElasticNet
ElasticNet_Reg = ElasticNet()
ElasticNet_Reg.fit (X_train, y_train )    

ElasticNet()

In [38]:
#==============================================================================
# Fitting the Decision Tree Regression algo to the Training set
#==============================================================================

from sklearn.tree import DecisionTreeRegressor
DT_Reg = DecisionTreeRegressor()
DT_Reg.fit (X_train, y_train )    

DecisionTreeRegressor()

In [39]:
#==============================================================================
# Fitting the Random Forest Regression algo to the Training set
#==============================================================================

from sklearn.ensemble import RandomForestRegressor
RF_Reg = RandomForestRegressor()
RF_Reg.fit (X_train, y_train )    

RandomForestRegressor()

In [40]:
#==============================================================================
# Fitting the SVM Regression algo to the Training set
#==============================================================================

from sklearn.svm import SVR
SV_Reg = SVR()
SV_Reg.fit (X_train, y_train )    

SVR()

In [44]:
!pip install xgboost
# check xgboost version
import xgboost
print(xgboost.__version__)

     --------------------------------------- 89.1/89.1 MB 13.6 MB/s eta 0:00:00
1.7.3


In [45]:
#==============================================================================
# Fitting the XGBoost algo to the Training set
#==============================================================================

from xgboost import XGBRegressor
XGBagent = XGBRegressor()
XGBagent.fit (X_train, y_train)            


XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [46]:
                   
#==============================================================================
# Now check what our model learned by predicting the X_train values
#==============================================================================

LR_train_preds=regressoragent.predict(X_train)
Lasso_train_preds=Lasso_Reg.predict(X_train)
Ridge_train__preds=Ridge_Reg.predict(X_train)
ElasticNet_train__preds=ElasticNet_Reg.predict(X_train)
DT_train__preds=DT_Reg.predict(X_train)
RF_train__preds=RF_Reg.predict(X_train)
SVR_train__preds=SV_Reg.predict(X_train)
XGBR_train__preds=XGBagent.predict(X_train)


In [47]:
                   
#==============================================================================
# Now check what our model learned by predicting the X_test values
#==============================================================================

LR_test_preds=regressoragent.predict(X_test)
Lasso_test_preds=Lasso_Reg.predict(X_test)
Ridge_test__preds=Ridge_Reg.predict(X_test)
ElasticNet_test__preds=ElasticNet_Reg.predict(X_test)
DT_test__preds=DT_Reg.predict(X_test)
RF_test__preds=RF_Reg.predict(X_test)
SVR_test__preds=SV_Reg.predict(X_test)
XGBR_test__preds=XGBagent.predict(X_test)



In [48]:
                   
#==============================================================================
# Now check our model performance with training set
#==============================================================================

from sklearn.metrics import r2_score

LR_train_r2=r2_score(y_train, LR_train_preds)
Lasso_train_r2=r2_score(y_train,Lasso_train_preds)
Ridge_train__r2=r2_score(y_train, Ridge_train__preds)
ElasticNet_train__r2=r2_score(y_train,ElasticNet_train__preds)
DT_train__r2=r2_score(y_train, DT_train__preds)
RF_train__r2=r2_score(y_train, RF_train__preds)
SVR_train__r2=r2_score(y_train, SVR_train__preds)
XGB_train__r2=r2_score(y_train, XGBR_train__preds)


In [49]:
print("LR r2 =", LR_train_r2)
print("Lasso r2 =", Lasso_train_r2)
print("Ridge r2 =", Ridge_train__r2)
print("ElasticNet r2 =", ElasticNet_train__r2)
print("DT r2 =", DT_train__r2)
print("RF r2 =", RF_train__r2)
print("SVR r2 =", SVR_train__r2)
print("XGB r2 =", XGB_train__r2)

LR r2 = 0.8119696662271327
Lasso r2 = 0.8119696662264587
Ridge r2 = 0.8119696662260674
ElasticNet r2 = 0.8119696659745858
DT r2 = 0.9784345862034002
RF r2 = 0.9441647201750683
SVR r2 = -0.0001004242756401652
XGB r2 = 0.9784345859262488


In [50]:
                 
#==============================================================================
# Now check our model performance with test set
#==============================================================================

LR_test_r2=r2_score(y_test, LR_test_preds)
Lasso_test_r2=r2_score(y_test,Lasso_test_preds)
Ridge_test__r2=r2_score(y_test, Ridge_test__preds)
ElasticNet_test__r2=r2_score(y_test,ElasticNet_test__preds)
DT_test__r2=r2_score(y_test, DT_test__preds)
RF_test__r2=r2_score(y_test, RF_test__preds)
SVR_test__r2=r2_score(y_test, SVR_test__preds)
XGB_test__r2=r2_score(y_test, XGBR_test__preds)

In [51]:
print("LR test r2 =", LR_test_r2)
print("Lasso test r2 =", Lasso_test_r2)
print("Ridge test r2 =", Ridge_test__r2)
print("ElasticNet test r2 =", ElasticNet_test__r2)
print("DT test r2 =", DT_test__r2)
print("RF test r2 =", RF_test__r2)
print("SVR test r2 =", SVR_test__r2)
print("XGB test r2 =", XGB_test__r2)


LR test r2 = 0.5667333126436415
Lasso test r2 = 0.5667338832983404
Ridge test r2 = 0.5667340300844952
ElasticNet test r2 = 0.5667443590588757
DT test r2 = 0.3039799100728704
RF test r2 = 0.5153046997673768
SVR test r2 = 0.0017161716437729124
XGB test r2 = 0.30398587607603633


In [52]:
print("LR train r2 =", LR_train_r2)
print("LR test r2 =", LR_test_r2)

print("Lasso train r2 =", Lasso_train_r2)
print("Lasso test r2 =", Lasso_test_r2)

print("Ridge train r2 =", Ridge_train__r2)
print("Ridge test r2 =", Ridge_test__r2)

print("ElasticNet train r2 =", ElasticNet_train__r2)
print("ElasticNet test r2 =", ElasticNet_test__r2)

print("DT train r2 =", DT_train__r2)
print("DT test r2 =", DT_test__r2)

print("RF train r2 =", RF_train__r2)
print("RF test r2 =", RF_test__r2)

print("SVR train r2 =", SVR_train__r2)
print("SVR test r2 =", SVR_test__r2)

print("XGB train r2 =", XGB_train__r2)
print("XGB test r2 =", XGB_test__r2)

LR train r2 = 0.8119696662271327
LR test r2 = 0.5667333126436415
Lasso train r2 = 0.8119696662264587
Lasso test r2 = 0.5667338832983404
Ridge train r2 = 0.8119696662260674
Ridge test r2 = 0.5667340300844952
ElasticNet train r2 = 0.8119696659745858
ElasticNet test r2 = 0.5667443590588757
DT train r2 = 0.9784345862034002
DT test r2 = 0.3039799100728704
RF train r2 = 0.9441647201750683
RF test r2 = 0.5153046997673768
SVR train r2 = -0.0001004242756401652
SVR test r2 = 0.0017161716437729124
XGB train r2 = 0.9784345859262488
XGB test r2 = 0.30398587607603633


In [53]:
ElasticNet_Reg_Opt = ElasticNet(alpha=0.9, l1_ratio=0.01)
ElasticNet_Reg_Opt.fit (X_train, y_train )

ElasticNet(alpha=0.9, l1_ratio=0.01)

In [54]:
ElasticNet_train_preds_opt=ElasticNet_Reg_Opt.predict(X_train)
ElasticNet_test_preds_opt=ElasticNet_Reg_Opt.predict(X_test)


In [55]:
ElasticNet_train_r2_Opt = r2_score(y_train,ElasticNet_train_preds_opt)
ElasticNet_test_r2_Opt = r2_score(y_test,ElasticNet_test_preds_opt)


In [56]:
print("ElasticNet train r2 =", ElasticNet_train__r2)
print("ElasticNet test r2 =", ElasticNet_test__r2)

ElasticNet train r2 = 0.8119696659745858
ElasticNet test r2 = 0.5667443590588757


In [57]:
print("ElasticNet train r2 Opt =", ElasticNet_train_r2_Opt)
print("ElasticNet test r2 Opt =", ElasticNet_test_r2_Opt)

ElasticNet train r2 Opt = 0.8119696654656692
ElasticNet test r2 Opt = 0.5667524933301655


In [58]:
print("ElasticNet train r2 Opt =", ElasticNet_train_r2_Opt)
print("ElasticNet test r2 Opt =", ElasticNet_test_r2_Opt)

ElasticNet train r2 Opt = 0.8119696654656692
ElasticNet test r2 Opt = 0.5667524933301655


In [59]:
dataset = [1000, 10]

In [60]:
ElasticNet_Reg_Opt.coef_ 

array([37.71562873])

In [61]:
ElasticNet_Reg.coef_

array([37.71611858])

In [62]:
ElasticNet_Reg_Opt.intercept_

16533.285447380847

In [63]:
ElasticNet_Reg.intercept_

16532.469039742347

In [64]:
from sklearn.metrics import mean_squared_error

LR_test_MSE=mean_squared_error(y_test, LR_test_preds)
Lasso_test_MSE=mean_squared_error(y_test,Lasso_test_preds)
Ridge_test__MSE=mean_squared_error(y_test, Ridge_test__preds)
ElasticNet_test__MSE=mean_squared_error(y_test,ElasticNet_test__preds)
DT_test_MSE=mean_squared_error(y_test, DT_test__preds)
RF_test_MSE=mean_squared_error(y_test, RF_test__preds)
SVR_test_MSE=mean_squared_error(y_test, SVR_test__preds)

In [65]:
LR_test_MSE

12782623.750405911

In [66]:
DT_Reg_2 = DecisionTreeRegressor(min_samples_leaf=6)
DT_Reg_2.fit (X_train, y_train )   

DecisionTreeRegressor(min_samples_leaf=6)

In [67]:
DT2_train_preds=DT_Reg_2.predict(X_train)
DT2_test_preds=DT_Reg_2.predict(X_test)


In [68]:
DT2_train_r2=r2_score(y_train, DT2_train_preds)
DT2_test_r2=r2_score(y_test, DT2_test_preds)


In [69]:
print("DT train r2 =", DT_train__r2)
print("DT test r2 =", DT_test__r2)

DT train r2 = 0.9784345862034002
DT test r2 = 0.3039799100728704


In [70]:
print("DT2 train r2 =", DT2_train_r2)
print("DT2 test r2 =", DT2_test_r2)

DT2 train r2 = 0.8069414930005423
DT2 test r2 = 0.5031483792930338


In [71]:
DT_Reg_2.tree_.node_count

7

In [72]:
DT_Reg_3 = DecisionTreeRegressor()


In [73]:
RF_Reg.estimators_

[DecisionTreeRegressor(max_features='auto', random_state=623013555),
 DecisionTreeRegressor(max_features='auto', random_state=578264554),
 DecisionTreeRegressor(max_features='auto', random_state=2081444978),
 DecisionTreeRegressor(max_features='auto', random_state=1327591710),
 DecisionTreeRegressor(max_features='auto', random_state=319516185),
 DecisionTreeRegressor(max_features='auto', random_state=121128227),
 DecisionTreeRegressor(max_features='auto', random_state=418385531),
 DecisionTreeRegressor(max_features='auto', random_state=110965071),
 DecisionTreeRegressor(max_features='auto', random_state=497947216),
 DecisionTreeRegressor(max_features='auto', random_state=2005068659),
 DecisionTreeRegressor(max_features='auto', random_state=169703367),
 DecisionTreeRegressor(max_features='auto', random_state=1438400758),
 DecisionTreeRegressor(max_features='auto', random_state=2067097147),
 DecisionTreeRegressor(max_features='auto', random_state=1406605932),
 DecisionTreeRegressor(max_f

In [74]:
XGBagent2 = XGBRegressor(max_depth=2)
XGBagent2.fit (X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=2, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [75]:
XGBR2_test__preds=XGBagent2.predict(X_test)


In [76]:
XGB2_test__r2=r2_score(y_test, XGBR2_test__preds)


In [77]:
XGB2_test__r2

0.32795408755786015